---
- hosts: localhost
  gather_facts: false

  tasks:
    - name: Test idempotency
      my_own_namespace.yandex_cloud_elk.my_own_module:
        path: /tmp/idempotent_test.txt
        content: "Idempotency check"
